chat:
  default:
    model:
      provider: openai
      model: gpt-4-0125-preview
    system_prompt: "Use Japanese default. Use Markdown for text decoration and code examples."
  llms:
    openai:
      api_key:
        type: env
        key: OPENAI_API_KEY
      models:
        gpt-3.5-turbo:
          display_name: "GPT-3.5"
          description: "あらゆるタスクに最適"
          # system_prompt: "Use Japanese default. Use Markdown for text decoration and code examples."
          token_limit: 4096
          allowed_roles: []
          variables:
            max_token:
              type: range
              default: 500
              min: 0
              max: 4000
              step: 200
            temperature:
              type: range
              default: 1.0
              min: 0.0
              max: 2.0
              step: 0.1
            top_p:
              default: 1.0
              type: range
              min: 0.0
              max: 1.0
              step: 0.1
            frequency_penalty:
              type: range
              default: 0.0
              min: -2.0
              max: 2.0
              step: 0.1
            presence_penalty:
              type: range
              default: 0.0
              min: -2.0
              max: 2.0
              step: 0.1
        gpt-4-0125-preview:
          display_name: "GPT-4-Turbo"
          description: "あらゆるタスクに最適"
          token_limit: 128000
          allowed_roles: []
          variables:
            max_token:
              type: range
              default: 500
              min: 0
              max: 4000
              step: 200
            temperature:
              type: range
              default: 1.0
              min: 0.0
              max: 2.0
              step: 0.1
            top_p:
              type: range
              default: 1.0
              min: 0.0
              max: 1.0
              step: 0.1
            frequency_penalty:
              type: range
              default: 0.0
              min: -2.0
              max: 2.0
              step: 0.1
            presence_penalty:
              type: range
              default: 0.0
              min: -2.0
              max: 2.0
              step: 0.1
    azure_openai:
      models:
        gpt-3.5-turbo:
          display_name: "GPT-3.5"
          description: "あらゆるタスクに最適"
          token_limit: 4096
          allowed_roles: ["Test.Test", "aa"]
          endpoint: https://your_aoai_service.openai.azure.com/
          api_key:
            type: env
            key: AZURE_OPENAI_API_KEY
          variables:
            max_token:
              type: range
              default: 500
              min: 0
              max: 4000
              step: 200
            temperature:
              type: range
              default: 1.0
              min: 0.0
              max: 2.0
              step: 0.1
            top_p:
              type: range
              default: 1.0
              min: 0.0
              max: 1.0
              step: 0.1
            frequency_penalty:
              type: range
              default: 0.0
              min: -2.0
              max: 2.0
              step: 0.1
            presence_penalty:
              type: range
              default: 0.0
              min: -2.0
              max: 2.0
              step: 0.1
        gpt-4:
          display_name: "GPT-4"
          description: "難しいタスクに最適"
          token_limit: 8192
          allowed_roles: []
          endpoint: https://your_aoai_service.openai.azure.com/
          api_key:
            type: env
            key: AZURE_OPENAI_API_KEY
          variables:
            max_token:
              type: range
              default: 500
              min: 0
              max: 8000
              step: 200
            temperature:
              type: range
              default: 1.0
              min: 0.0
              max: 2.0
              step: 0.1
            top_p:
              type: range
              default: 1.0
              min: 0.0
              max: 1.0
              step: 0.1
            frequency_penalty:
              type: range
              default: 0.0
              min: -2.0
              max: 2.0
              step: 0.1
            presence_penalty:
              type: range
              default: 0.0
              min: -2.0
              max: 2.0
              step: 0.1
