version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ..:/workspace:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  postgres:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

    # Use "network_mode: service:app" to share the network stack with the app container.
    # This means you can connect to PostgreSQL from the app container using "localhost".
    # Be sure to update the connection string to use "localhost".
    #network_mode: service:app

    # Add "forwardPorts": ["5432"] or ["postgres:5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # Note: Use "forwardPorts": ["5432"] if you are using the network_mode property, otherwise use "forwardPorts": ["postgres:5432"].
    # (Adding the "ports" property to this file will not forward from a Codespace.)

volumes:
  postgres-data:
